sonar.organization=angelopohl
sonar.projectKey=angelopohl_Plataforma_Microcreditos-IaC
sonar.projectName=Plataforma Microcreditos IaC

# Código que analizará SonarQube
sonar.sources=iac,app/backend,app/frontend/src

sonar.sourceEncoding=UTF-8

# Versión del provider AWS usada por Terraform
sonar.terraform.provider.aws.version=5.37.0

# Archivos y carpetas generadas o sensibles
sonar.exclusions=**/.terraform/**,**/node_modules/**,**/dist/**,**/*.tfstate,**/*.tfstate.*,**/terraform.tfvars,**/*.auto.tfvars,**/.env,**/.env.*,**/package-lock.json