# checkov:skip=CKV2_GHA_1: Los permisos se gestionan a nivel de organización o son necesarios para la acción de Checkov.
name: CD - Checkov

on:
  push:
    branches:
      - dev
    paths:
      - ".github/workflows/cd-checkov.yml"
      - "IaC_/**"

  workflow_dispatch:

jobs:
  checkov-audit:
    name: Checkov reporte
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Ejecutar Checkov vía Docker
        id: checkov
        continue-on-error: true
        run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            -v "$(pwd):/repo" \
            --workdir /repo \
            bridgecrew/checkov:3 \
            --directory /repo/IaC_ \
            -o junitxml \
            --output-file-path /repo/

      - name: Guardar reporte de Checkov
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: checkov-security-report
          path: results_junitxml.xml
          if-no-files-found: ignore

      - name: Enviar reporte de Checkov por correo
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Resultados de Checkov - ${{ github.repository }}
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions
          body: Se ha completado el análisis de Checkov. Adjunto encontrarás los resultados (results_junitxml.xml).
          attachments: results_junitxml.xml